<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Data Science - 9&nbsp; Statistical Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./supervised.html" rel="next">
<link href="./visualization.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./statsmod.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Statistical Models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/ids-s24.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preliminaries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Project Management</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Reproducibile Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Python Refreshment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Import/Export</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./communication.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Communication and Ethics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statsmod.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Statistical Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./supervised.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Supervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Advanced Topics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">9.1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#installation-of-statsmodels" id="toc-installation-of-statsmodels" class="nav-link" data-scroll-target="#installation-of-statsmodels"><span class="header-section-number">9.1.1</span> Installation of <code>statsmodels</code></a></li>
  <li><a href="#features-of-statsmodels" id="toc-features-of-statsmodels" class="nav-link" data-scroll-target="#features-of-statsmodels"><span class="header-section-number">9.1.2</span> Features of <code>statsmodels</code></a></li>
  </ul></li>
  <li><a href="#generalized-linear-models" id="toc-generalized-linear-models" class="nav-link" data-scroll-target="#generalized-linear-models"><span class="header-section-number">9.2</span> Generalized Linear Models</a></li>
  <li><a href="#statistical-modeling-with-statsmodels" id="toc-statistical-modeling-with-statsmodels" class="nav-link" data-scroll-target="#statistical-modeling-with-statsmodels"><span class="header-section-number">9.3</span> Statistical Modeling with <code>statsmodels</code></a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1"><span class="header-section-number">9.3.1</span> Introduction</a></li>
  <li><a href="#key-features-and-capabilities" id="toc-key-features-and-capabilities" class="nav-link" data-scroll-target="#key-features-and-capabilities"><span class="header-section-number">9.3.2</span> Key Features and Capabilities</a></li>
  <li><a href="#installation-and-setup" id="toc-installation-and-setup" class="nav-link" data-scroll-target="#installation-and-setup"><span class="header-section-number">9.3.3</span> Installation and Setup</a></li>
  <li><a href="#importing-data" id="toc-importing-data" class="nav-link" data-scroll-target="#importing-data"><span class="header-section-number">9.3.4</span> Importing Data</a></li>
  <li><a href="#troubleshooting" id="toc-troubleshooting" class="nav-link" data-scroll-target="#troubleshooting"><span class="header-section-number">9.3.5</span> Troubleshooting</a></li>
  <li><a href="#statistical-modeling-and-analysis" id="toc-statistical-modeling-and-analysis" class="nav-link" data-scroll-target="#statistical-modeling-and-analysis"><span class="header-section-number">9.3.6</span> Statistical Modeling and Analysis</a></li>
  <li><a href="#generalized-linear-models-1" id="toc-generalized-linear-models-1" class="nav-link" data-scroll-target="#generalized-linear-models-1"><span class="header-section-number">9.3.7</span> Generalized Linear Models</a></li>
  <li><a href="#diagnostic-tests" id="toc-diagnostic-tests" class="nav-link" data-scroll-target="#diagnostic-tests"><span class="header-section-number">9.3.8</span> Diagnostic Tests</a></li>
  <li><a href="#nonparametric-models" id="toc-nonparametric-models" class="nav-link" data-scroll-target="#nonparametric-models"><span class="header-section-number">9.3.9</span> Nonparametric Models</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">9.3.10</span> References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Statistical Models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">9.1</span> Introduction</h2>
<p>Statistical modeling is a cornerstone of data science, offering tools to understand complex relationships within data and to make predictions. Python, with its rich ecosystem for data analysis, features the <code>statsmodels</code> package— a comprehensive library designed for statistical modeling, tests, and data exploration. <code>statsmodels</code> stands out for its focus on classical statistical models and compatibility with the Python scientific stack (<code>numpy</code>, <code>scipy</code>, <code>pandas</code>).</p>
<section id="installation-of-statsmodels" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="installation-of-statsmodels"><span class="header-section-number">9.1.1</span> Installation of <code>statsmodels</code></h3>
<p>To start with statistical modeling, ensure <code>statsmodels</code> is installed:</p>
<p>Using pip:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install statsmodels</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="features-of-statsmodels" class="level3" data-number="9.1.2">
<h3 data-number="9.1.2" class="anchored" data-anchor-id="features-of-statsmodels"><span class="header-section-number">9.1.2</span> Features of <code>statsmodels</code></h3>
<p>Package <code>statsmodels</code> offers a comprehensive range of statistical models and tests, making it a powerful tool for a wide array of data analysis tasks:</p>
<ul>
<li><p><strong>Linear Regression Models</strong>: Essential for predicting quantitative responses, these models form the backbone of many statistical analysis operations.</p></li>
<li><p><strong>Generalized Linear Models (GLM)</strong>: Expanding upon linear models, GLMs allow for response variables that have error distribution models other than a normal distribution, catering to a broader set of data characteristics.</p></li>
<li><p><strong>Time Series Analysis</strong>: This includes models like ARIMA for analyzing and forecasting time-series data, as well as more complex state space models and seasonal decompositions.</p></li>
<li><p><strong>Nonparametric Methods</strong>: For data that does not fit a standard distribution, <code>statsmodels</code> provides tools like kernel density estimation and smoothing techniques.</p></li>
<li><p><strong>Statistical Tests</strong>: A suite of hypothesis testing tools allows users to rigorously evaluate their models and assumptions, including diagnostics for model evaluation.</p></li>
</ul>
<p>Integrating <code>statsmodels</code> into your data science workflow enriches your analytical capabilities, allowing for both exploratory data analysis and complex statistical modeling.</p>
</section>
</section>
<section id="generalized-linear-models" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="generalized-linear-models"><span class="header-section-number">9.2</span> Generalized Linear Models</h2>
<p>Generalized Linear Models (GLM) extend the classical linear regression to accommodate response variables, that follow distributions other than the normal distribution. GLMs consist of three main components:</p>
<ul>
<li><strong>Random Component</strong>: This specifies the distribution of the response variable <span class="math inline">\(Y\)</span>. It is assumed to be from the exponential family of distributions, such as Binomial for binary data and Poisson for count data.</li>
<li><strong>Systematic Component</strong>: This consists of the linear predictor, a linear combination of unknown parameters and explanatory variables. It is denoted as <span class="math inline">\(\eta = X\beta\)</span>, where <span class="math inline">\(X\)</span> represents the explanatory variables, and <span class="math inline">\(\beta\)</span> represents the coefficients.</li>
<li><strong>Link Function</strong>: The link function, <span class="math inline">\(g\)</span>, provides the relationship between the linear predictor and the mean of the distribution function. For a GLM, the mean of <span class="math inline">\(Y\)</span> is related to the linear predictor through the link function as <span class="math inline">\(\mu = g^{-1}(\eta)\)</span>.</li>
</ul>
<p>Generalized Linear Models (GLM) adapt to various data types through the selection of appropriate link functions and probability distributions. Here, we outline four special cases of GLM: normal regression, logistic regression, Poisson regression, and gamma regression.</p>
<ul>
<li>Normal Regression (Linear Regression). In normal regression, the response variable has a normal distribution. The identity link function (<span class="math inline">\(g(\mu) = \mu\)</span>) is typically used, making this case equivalent to classical linear regression.
<ul>
<li><strong>Use Case</strong>: Modeling continuous data where residuals are normally distributed.</li>
<li><strong>Link Function</strong>: Identity (<span class="math inline">\(g(\mu) = \mu\)</span>)</li>
<li><strong>Distribution</strong>: Normal</li>
</ul></li>
<li>Logistic Regression. Logistic regression is used for binary response variables. It employs the logit link function to model the probability that an observation falls into one of two categories.
<ul>
<li><strong>Use Case</strong>: Binary outcomes (e.g., success/failure).</li>
<li><strong>Link Function</strong>: Logit (<span class="math inline">\(g(\mu) = \log\frac{\mu}{1-\mu}\)</span>)</li>
<li><strong>Distribution</strong>: Binomial</li>
</ul></li>
<li>Poisson Regression. Poisson regression models count data using the Poisson distribution. It’s ideal for modeling the rate at which events occur.
<ul>
<li><strong>Use Case</strong>: Count data, such as the number of occurrences of an event.</li>
<li><strong>Link Function</strong>: Log (<span class="math inline">\(g(\mu) = \log(\mu)\)</span>)</li>
<li><strong>Distribution</strong>: Poisson</li>
</ul></li>
<li>Gamma Regression. Gamma regression is suited for modeling positive continuous variables, especially when data are skewed and variance increases with the mean.
<ul>
<li><strong>Use Case</strong>: Positive continuous outcomes with non-constant variance.</li>
<li><strong>Link Function</strong>: Inverse (<span class="math inline">\(g(\mu) = \frac{1}{\mu}\)</span>)</li>
<li><strong>Distribution</strong>: Gamma</li>
</ul></li>
</ul>
<p>Each GLM variant addresses specific types of data and research questions, enabling precise modeling and inference based on the underlying data distribution.</p>
</section>
<section id="statistical-modeling-with-statsmodels" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="statistical-modeling-with-statsmodels"><span class="header-section-number">9.3</span> Statistical Modeling with <code>statsmodels</code></h2>
<p>This section was written by Leon Nguyen.</p>
<section id="introduction-1" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="introduction-1"><span class="header-section-number">9.3.1</span> Introduction</h3>
<p>Hello! My name is Leon Nguyen (they/she) and I am a second-year undergraduate student studying Statistical Data Science and Mathematics at the University of Connecticut, aiming to graduate in Fall 2025. One of my long-term goals is to make the field of data science more accessible to marginalized communities and minority demographics. My research interests include data visualization and design. Statistical modeling is one of the most fundamental skills required for data science, and it’s important to have a solid understanding of how models work for interpretable results.</p>
<p>The <code>statsmodels</code> Python package offers a diverse range of classes and functions tailored for estimating various statistical models, conducting statistical tests, and exploring statistical data. Each estimator provides an extensive array of result statistics, rigorously tested against established statistical packages to ensure accuracy. This presentation will focus on the practical applications of the statistical modeling aspect.</p>
</section>
<section id="key-features-and-capabilities" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="key-features-and-capabilities"><span class="header-section-number">9.3.2</span> Key Features and Capabilities</h3>
<p>Some key features and capabilities of <code>statsmodels</code> are:</p>
<ul>
<li>Generalized Linear Models</li>
<li>Diagnostic Tests</li>
<li>Nonparametric methods</li>
</ul>
<p>In this presentation, we will work with practical applications of statistical modeling in <code>statsmodels</code>. We will briefly cover how to set up linear, logistic, and Poisson regression models, and touch upon kernel density estimation and diagnostics. By the end of this presentation, you should be able to understand how to use <code>statsmodels</code> to analyze your own datasets using these fundamental techniques.</p>
</section>
<section id="installation-and-setup" class="level3" data-number="9.3.3">
<h3 data-number="9.3.3" class="anchored" data-anchor-id="installation-and-setup"><span class="header-section-number">9.3.3</span> Installation and Setup</h3>
<p>To install <code>statsmodels</code>, use <code>pip install statsmodels</code> or <code>conda install statsmodels</code>, depending on whether you are using pip or conda.</p>
<p>One of the major benefits of using <code>statsmodels</code> is their compatability with other commnonly used packages, such as <code>NumPy</code>, <code>SciPy</code>, and <code>Pandas</code>. These packages provide foundational scientific computing functionalities that are crucial for working with <code>statsmodels</code>. To ensure everything is set up correctly, import the necessary libraries at the beginning of your script:</p>
<div id="4a93091e" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are some minimum dependencies:</p>
<ul>
<li>Python &gt;= 3.8</li>
<li>NumPy &gt;= 1.18</li>
<li>SciPy &gt;= 1.4</li>
<li>Pandas &gt;= 1.0</li>
<li>Patsy &gt;= 0.5.2</li>
</ul>
<p>The last item listed above, <code>patsy</code>, is a Python library that provides simple syntax for specifying statistical models in Python. It allows users to define linear models using a formula syntax similar to the formulas used in R and other statistical software. More <code>patsy</code> documentation can be found <a href="https://patsy.readthedocs.io/en/latest/">here</a>. This library is not used this demonstration, but is still worth noting.</p>
</section>
<section id="importing-data" class="level3" data-number="9.3.4">
<h3 data-number="9.3.4" class="anchored" data-anchor-id="importing-data"><span class="header-section-number">9.3.4</span> Importing Data</h3>
<p>There are a few different options to import data. For example, <code>statsmodels</code> documentation demonstrates how to importing from a CSV file hosted online from the <a href="https://github.com/vincentarelbundock/Rdatasets/">Rdatasets repository</a>:</p>
<div id="3b3ca2df" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reads the 'avocado' dataset from the causaldata package into df</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df0 <span class="op">=</span> sm.datasets.get_rdataset(dataname<span class="op">=</span><span class="st">'avocado'</span>, package<span class="op">=</span><span class="st">"causaldata"</span>).data</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># We will be using this dataset later!</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print out the first five rows of our dataframe</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df0.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Date  AveragePrice  TotalVolume
0  2015-12-27          0.90   5040365.47
1  2015-12-20          0.94   4695737.21
2  2015-12-13          0.87   5259354.30
3  2015-12-06          0.78   5775536.27
4  2015-11-29          0.91   4575710.62</code></pre>
</div>
</div>
<p>We can also read directly from a local CSV file with <code>pandas</code>. For example, we will be using the NYC 311 request rodent data:</p>
<div id="a06affc5" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reads the csv file into df</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'data/rodent_2022-2023.csv'</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Brief data pre-processing</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Time reformatting</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Created Date'</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">'Created Date'</span>], <span class="bu">format</span> <span class="op">=</span> <span class="st">"%m/</span><span class="sc">%d</span><span class="st">/%Y %I:%M:%S %p"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Closed Date'</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">'Closed Date'</span>], <span class="bu">format</span> <span class="op">=</span> <span class="st">"%m/</span><span class="sc">%d</span><span class="st">/%Y %I:%M:%S %p"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Created Year'</span>] <span class="op">=</span> df[<span class="st">'Created Date'</span>].dt.year</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Created Month'</span>] <span class="op">=</span> df[<span class="st">'Created Date'</span>].dt.month</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Response time</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Response Time'</span>] <span class="op">=</span> df[<span class="st">'Closed Date'</span>] <span class="op">-</span> df[<span class="st">'Created Date'</span>] </span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Response Time'</span>] <span class="op">=</span> df[<span class="st">'Response Time'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: x.total_seconds() <span class="op">/</span> <span class="dv">3600</span>) <span class="co"># in hours</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove unspecified borough rows</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(df[df[<span class="st">'Borough'</span>]<span class="op">==</span><span class="st">'Unspecified'</span>].index)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove 'other' open data channel type rows</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(df[df[<span class="st">'Open Data Channel Type'</span>]<span class="op">==</span><span class="st">'OTHER'</span>].index)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Unique Key        Created Date         Closed Date Agency  \
0    59893776 2023-12-31 23:05:41 2023-12-31 23:05:41  DOHMH   
1    59887523 2023-12-31 22:19:22 2024-01-03 08:47:02  DOHMH   
2    59891998 2023-12-31 22:03:12 2023-12-31 22:03:12  DOHMH   
3    59887520 2023-12-31 21:13:02 2024-01-03 09:33:43  DOHMH   
4    59889297 2023-12-31 20:50:10                 NaT  DOHMH   

                               Agency Name Complaint Type      Descriptor  \
0  Department of Health and Mental Hygiene         Rodent    Rat Sighting   
1  Department of Health and Mental Hygiene         Rodent    Rat Sighting   
2  Department of Health and Mental Hygiene         Rodent    Rat Sighting   
3  Department of Health and Mental Hygiene         Rodent  Mouse Sighting   
4  Department of Health and Mental Hygiene         Rodent    Rat Sighting   

             Location Type  Incident Zip      Incident Address  ...  \
0  3+ Family Apt. Building         11216     265 PUTNAM AVENUE  ...   
1      Commercial Building         10028     1538 THIRD AVENUE  ...   
2  3+ Family Apt. Building         10458   2489 TIEBOUT AVENUE  ...   
3  3+ Family Apt. Building         11206  116 JEFFERSON STREET  ...   
4      1-2 Family Dwelling         11206     114 ELLERY STREET  ...   

                                   Location Zip Codes Community Districts  \
0  (40.683855196486164, -73.95164557951071)   17618.0                69.0   
1   (40.77924175816874, -73.95368859796383)   10099.0                23.0   
2  (40.861693023118924, -73.89499228560491)   10936.0                 6.0   
3   (40.69974221739347, -73.93073474327662)   17213.0                42.0   
4   (40.69844506428295, -73.94858040356128)   17213.0                69.0   

  Borough Boundaries City Council Districts Police Precincts Police Precinct  \
0                2.0                   49.0             51.0            51.0   
1                4.0                    1.0             11.0            11.0   
2                5.0                   22.0             29.0            29.0   
3                2.0                   30.0             53.0            53.0   
4                2.0                   49.0             51.0            51.0   

  Created Year  Created Month Response Time  
0         2023             12      0.000000  
1         2023             12     58.461111  
2         2023             12      0.000000  
3         2023             12     60.344722  
4         2023             12           NaN  

[5 rows x 50 columns]</code></pre>
</div>
</div>
</section>
<section id="troubleshooting" class="level3" data-number="9.3.5">
<h3 data-number="9.3.5" class="anchored" data-anchor-id="troubleshooting"><span class="header-section-number">9.3.5</span> Troubleshooting</h3>
<p>Whenever you are having problems with <code>statsmodels</code>, you can access the official documentation by visiting <a href="https://www.statsmodels.org/stable/index.html">this link</a>. If you are working in a code editor, you can also run the following in a code cell:</p>
<div id="e3525cde" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sm.webdoc() </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Opens the official documentation page in your browser</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To look for specific documentation, for example <code>sm.GLS</code>, you can run the following:</p>
<div id="993b93b4" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sm.webdoc(func<span class="op">=</span>sm.GLS, stable<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># func : string* or function to search for documentation </span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># stable : (True) or development (False) documentation, default is stable</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># *Searching via string has presented issues?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="statistical-modeling-and-analysis" class="level3" data-number="9.3.6">
<h3 data-number="9.3.6" class="anchored" data-anchor-id="statistical-modeling-and-analysis"><span class="header-section-number">9.3.6</span> Statistical Modeling and Analysis</h3>
<p>Constructing statistical models with <code>statsmodels</code> generally follows a step-by-step process:</p>
<ol type="1">
<li><p><strong>Import necessary libraries</strong>: This includes both <code>numpy</code> and <code>pandas</code>, as well as <code>statsmodels.api</code> itself (<code>sm</code>).</p></li>
<li><p><strong>Load</strong> the data: This could be data from the <code>rdataset</code> repository, local csv files, or other formats. In general, it’s best practice to load your data into a <code>pandas</code> DataFrame so that it can easily be manipulated using <code>pandas</code> functions.</p></li>
<li><p><strong>Prepare the data</strong>: This involves converting variables into appropriate types (e.g., categorical into factors), handling missing values, and creating appropriate interaction terms.</p></li>
<li><p><strong>Define</strong> our model: what model is the appropriate representation of our research question? This could be an OLS regression (<code>sm.OLS</code>), logistic regression (<code>sm.Logit</code>), or any number of other models depending on the nature of our data.</p></li>
<li><p><strong>Fit</strong> the model to our data: we use the <code>.fit()</code> method which takes as input our dependent variable and independent variables.</p></li>
<li><p><strong>Analyze</strong> the results of the model: this is where we can get things like parameter estimates, standard errors, p-values, etc. We use the <code>.summary()</code> method to print out these statistics.</p></li>
</ol>
</section>
<section id="generalized-linear-models-1" class="level3" data-number="9.3.7">
<h3 data-number="9.3.7" class="anchored" data-anchor-id="generalized-linear-models-1"><span class="header-section-number">9.3.7</span> Generalized Linear Models</h3>
<p>GLM models allow us to construct a linear relationship between the response and predictors, even if their underlying relationship is not linear. This is done via a link function, which is a transformation which links the response variable to a linear model.</p>
<p>Key points of GLMs:</p>
<ul>
<li>Data should be independent and random.</li>
<li>The response variable <span class="math inline">\(Y\)</span> does not need to be normally distributed, but the distribution is from an exponential family (e.g.&nbsp;binomial, Poisson, normal).</li>
<li>GLMs do not assume a linear relationship between the response variable and the explanatory variables, but assume a linear relationship between the transformed expected response in terms of the link function and the explanatory variables.</li>
<li>GLMs are useful when the range of your response variable is constrained and/or the variance is not constant or normally distributed.</li>
<li>GLM models transform the response variable to allow the fit to be done by least squares. The transformation done on the response variable is defined by the link function.</li>
</ul>
<section id="linear-regression" class="level4" data-number="9.3.7.1">
<h4 data-number="9.3.7.1" class="anchored" data-anchor-id="linear-regression"><span class="header-section-number">9.3.7.1</span> Linear Regression</h4>
<p>Simple and muliple linear regression are special cases where the expected value of the dependent value is equal to a linear combination of predictors. In other words, the link function is the identity function <span class="math inline">\(g[E(Y)]=E(Y)\)</span>. Make sure assumptions for linear regression hold before proceeding. The model for linear regression is given by: <span class="math display">\[y_i = X_i\beta + \epsilon_i\]</span> where <span class="math inline">\(X_i\)</span> is a vector of predictors for individual <span class="math inline">\(i\)</span>, and <span class="math inline">\(\beta\)</span> is a vector of coefficients that define this linear combination.</p>
<p>We will be working with the <code>avocado</code> dataset from the package <code>causaldata</code> which contains information about the average price and total amount of avocados that were sold in California from 2015-2018. <code>AveragePrice</code> of a single avocado is our predictor, and <code>TotalVolume</code> is our outcome variable as a count of avocados.</p>
<p>Here is an application of SLR with <code>statsmodels</code>:</p>
<div id="becceac5" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can use .get_rdataset() to load data into Python from a repositiory of R packages.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="op">=</span> sm.datasets.get_rdataset(<span class="st">'avocado'</span>, package<span class="op">=</span><span class="st">"causaldata"</span>).data</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>results1 <span class="op">=</span> smf.ols(<span class="st">'TotalVolume ~ AveragePrice'</span>, data<span class="op">=</span>df1).fit()</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Analyze results</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results1.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:            TotalVolume   R-squared:                       0.441
Model:                            OLS   Adj. R-squared:                  0.438
Method:                 Least Squares   F-statistic:                     132.0
Date:                Mon, 25 Mar 2024   Prob (F-statistic):           7.04e-23
Time:                        16:27:18   Log-Likelihood:                -2550.3
No. Observations:                 169   AIC:                             5105.
Df Residuals:                     167   BIC:                             5111.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     9.655e+06    3.3e+05     29.222      0.000       9e+06    1.03e+07
AveragePrice -3.362e+06   2.93e+05    -11.487      0.000   -3.94e+06   -2.78e+06
==============================================================================
Omnibus:                       50.253   Durbin-Watson:                   0.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              165.135
Skew:                           1.135   Prob(JB):                     1.38e-36
Kurtosis:                       7.278   Cond. No.                         9.83
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>We can interpret some values:</p>
<ul>
<li><strong>coef:</strong> the coefficient of <code>AveragePrice</code> tells us how much adding one unit of <code>AveragePrice</code> changes the predicted value of <code>TotalVolume</code>. An important interpretation is that if <code>AveragePrice</code> was to increase by one unit, on average we could expect <code>TotalVolume</code> to change by this coefficient based on this linear model. This makes sense since higher prices should result in a smaller amount of avocados sold.</li>
<li><strong>P&gt;|t|:</strong> p-value to test significant effect of the predictor on the response, compared to a significance level <span class="math inline">\(\alpha=0.05\)</span>. When this p-value <span class="math inline">\(\leq \alpha\)</span>, we would reject the null hypothesis that there is no effect of <code>AveragePrice</code> on <code>TotalVolume</code>, and conclude that <code>AveragePrice</code> has a statistically significant effect on <code>TotalVolume</code>.</li>
<li><strong>R-squared:</strong> indicates the proportion of variance explained by the predictors (in this case just <code>AveragePrice</code>). If it’s close to 1 then most of the variability in <code>TotalVolume</code> is explained by <code>AveragePrice</code>, which is good! However, only about 44.1% of the variability is explained, so this model could use some improvement.</li>
<li><strong>Prob (F-statistic):</strong> indicates whether or not the linear regression model provides a better fit to a dataset than a model with no predictors. Assuming a significance level of 0.05, we would reject the null hypothesis (model with just the intercept does just as well with a model with predictors) since our F-value probability is less than 0.05. We know that <code>AveragePrice</code> gives at least some significant information about <code>TotalVolume</code>. (This makes more sense in MLR where you are considering multiple predictors.)</li>
<li><strong>Skew:</strong> measures asymmetry of a distribution, which can be positive, negative, or zero. If skewness is positive, the distribution is more skewed to the right; if negative, then to the left. We ideally want a skew value of zero in a normal distribution.</li>
<li><strong>Kurtosis:</strong> a measure of whether or not a distribution is heavy-tailed or light-tailed relative to a normal distribution. For a normal distribution, we expect a kurtosis of 3. If our kurtosis is greater than 3, there are more outliers on the tails. If less than 3, then there are less.</li>
<li><strong>Prob (Jarque-Bera):</strong> indicates whether or not the residuals are normally distributed, which is required for the OLS linear regression model. In this case the test rejects the null hypothesis that the residuals come from a normal distribution. This is concerning because non-normality can lead to misleading conclusions and incorrect standard errors.</li>
</ul>
</section>
<section id="logistic-regression" class="level4" data-number="9.3.7.2">
<h4 data-number="9.3.7.2" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">9.3.7.2</span> Logistic Regression</h4>
<p>Logistic regression is used when the response variable is binary. The response distribution is logistic which means it has support (input) on <span class="math inline">\((0,1)\)</span> and<br>
is invertible. The log-odds link function is defined as <span class="math inline">\(\log\left(\frac{\mu}{1-\mu}\right)\)</span>, where <span class="math inline">\(\mu\)</span> is the predicted probability.</p>
<p>Here we have an example from our <code>rodents</code> dataset, where the response variable <code>Under 3h</code> indicates whether the response time for a 311 service request was under 3 hours. 1 indicates that the response time is less than 3 hours, and 0 indications greater than or equal to 3 hours. We are creating a logistic regression model that can be used to estimate the odds ratio of 311 requests having a response time under 3 hours based on <code>Borough</code> and <code>Open Data Channel Type</code> (method of how 311 service request was submitted) as predictors.</p>
<div id="41ce2e5c" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loaded the dataset in a previous cell as df</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create binary variable</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Under 3h'</span>] <span class="op">=</span> (df[<span class="st">'Response Time'</span>] <span class="op">&lt;</span> <span class="dv">3</span>).astype(<span class="bu">int</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the categorical variable to dummy variables</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.loc[:, [<span class="st">'Borough'</span>, <span class="st">'Open Data Channel Type'</span>, <span class="st">'Under 3h'</span>]]</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.get_dummies(df, dtype <span class="op">=</span> <span class="bu">int</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove reference dummy variables</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>df.drop(</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  columns<span class="op">=</span>[<span class="st">'Borough_QUEENS'</span>, <span class="st">'Open Data Channel Type_MOBILE'</span>], </span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  axis<span class="op">=</span><span class="dv">1</span>, </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  inplace<span class="op">=</span><span class="va">True</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For this regression to run properly, we needed to create <span class="math inline">\(k-1\)</span> dummy variables with <span class="math inline">\(k\)</span> levels in a given predictor. Here we have two categorical variables that we used <code>pd.get_dummies()</code> function to change from a categorical variable into dummy variables. We then dropped one dummy variable level from each category: <code>'Borough_QUEENS'</code> and <code>'Open Data Channel Type_MOBILE'</code>.</p>
<div id="d6675457" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop all rows with NaN values</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>df.dropna(inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the logistic regression model using statsmodels</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> df[<span class="st">'Under 3h'</span>]</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(df.drop(columns <span class="op">=</span> <span class="st">'Under 3h'</span>, axis<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># need to consider constant manually</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>logitmod <span class="op">=</span> sm.Logit(Y, X)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> logitmod.fit(maxiter<span class="op">=</span><span class="dv">30</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the fitted model</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.616020
         Iterations 5
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Under 3h   No. Observations:                82846
Model:                          Logit   Df Residuals:                    82839
Method:                           MLE   Df Model:                            6
Date:                Mon, 25 Mar 2024   Pseudo R-squ.:                 0.02459
Time:                        16:27:19   Log-Likelihood:                -51035.
converged:                       True   LL-Null:                       -52321.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=================================================================================================
                                    coef    std err          z      P&gt;|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const                             0.8691      0.022     39.662      0.000       0.826       0.912
Borough_BRONX                     0.1051      0.029      3.644      0.000       0.049       0.162
Borough_BROOKLYN                 -0.4675      0.023    -20.232      0.000      -0.513      -0.422
Borough_MANHATTAN                -0.7170      0.024    -29.892      0.000      -0.764      -0.670
Borough_STATEN ISLAND             0.0122      0.050      0.243      0.808      -0.086       0.110
Open Data Channel Type_ONLINE     0.2933      0.019     15.402      0.000       0.256       0.331
Open Data Channel Type_PHONE      0.4540      0.018     25.836      0.000       0.420       0.488
=================================================================================================</code></pre>
</div>
</div>
<ul>
<li><p><strong>coef:</strong> the coefficients of the independent variables in the logistic regression equation are interpreted a little bit differently than linear regression; for example, if <code>borough_MANHATTAN</code> increases by one unit and all else is held constant, we expect the <em>log odds</em> to decrease by 0.7192 units. According to this model, we can expect it is less likely for response time to be under three hours for a 311 service request in Manhattan compared to Queens (reference level). On the other hand, if <code>borough_BRONX</code> increases by one unit and all else is held constant, we expect the log odds to increase by 0.1047 units. We can expect it is more likely for response time to be under three hours for a 311 service request in the Bronx compared to Queens. If we want to look at comparisons between <code>Open Data Channel Type</code>, from this model, we can also see that 311 requests in the dataset that were submitted via phone call are more likely to have a response time under three hours compared to those that were submitted via mobile.</p></li>
<li><p><strong>Log-Likelihood:</strong> the natural logarithm of the Maximum Likelihood Estimation(MLE) function. MLE is the optimization process of finding the set of parameters that result in the best fit. Log-likelihood on its own doesn’t give us a lot of information, but comparing this value from two different models with the same number of predictors can be useful. Higher log-likelihood indicates a better fit.</p></li>
<li><p><strong>LL-Null:</strong> the value of log-likelihood of the null model (model with no predictors, just intercept).</p></li>
<li><p><strong>Pseudo R-squ.:</strong> similar but not exact equivalent to the R-squared value in Least Squares linear regression. This is also known as McFadden’s R-Squared, and is computed as <span class="math inline">\(1-\dfrac{L_1}{L_0}\)</span>, where <span class="math inline">\(L_0\)</span> is the log-likelihood of the null model and <span class="math inline">\(L_1\)</span> is that of the full model.</p></li>
<li><p><strong>LLR p-value:</strong> the p-value of log-likelihood ratio test statistic comparing the full model to the null model. Assuming a significance level <span class="math inline">\(\alpha\)</span> of 0.05, if this p-value <span class="math inline">\(\leq \alpha,\)</span> then we reject the null hypothesis that the model is not significant. We reject the null hypothesis; thus we can conclude this model has predictors that are significant (non-zero coefficients).</p></li>
</ul>
<p>Another example:</p>
<p>We will use the <code>macrodata</code> dataset directly from <code>statsmodels</code>, which contains information on macroeconomic indicators in the US across different quarters from 1959 to 2009, such as unemployment rate, inflation rate, real gross domestic product, etc. I have created a binary variable <code>morethan5p</code> that has a value of 1 when the unemployment rate is more than 5% in a given quarter, and is 0 when it is equal to or less than 5%. We are creating a logistic regression model that can be used to estimate the odds ratio of the unemployment rate being greater than 5% based on <code>cpi</code> (end-of-quarter consumer price index) and <code>pop</code> (end-of-quarter population) as predictors.</p>
<div id="457c9eec" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># df2 is an instance of a statsmodels dataset class</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="op">=</span> sm.datasets.macrodata.load_pandas()</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># add binary variable</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>df2.data[<span class="st">'morethan5p'</span>] <span class="op">=</span> (df2.data[<span class="st">'unemp'</span>]<span class="op">&gt;</span><span class="dv">5</span>).<span class="bu">apply</span>(<span class="kw">lambda</span> x:<span class="bu">int</span>(x))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset data</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>df2 <span class="op">=</span> df2.data[[<span class="st">'morethan5p'</span>,<span class="st">'cpi'</span>,<span class="st">'pop'</span>]]</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Logit regression model</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.logit(<span class="st">"morethan5p ~ cpi + pop"</span>, df2)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>result2 <span class="op">=</span> model.fit()</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> result2.summary()</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.559029
         Iterations 6
                           Logit Regression Results                           
==============================================================================
Dep. Variable:             morethan5p   No. Observations:                  203
Model:                          Logit   Df Residuals:                      200
Method:                           MLE   Df Model:                            2
Date:                Mon, 25 Mar 2024   Pseudo R-squ.:                 0.05839
Time:                        16:27:19   Log-Likelihood:                -113.48
converged:                       True   LL-Null:                       -120.52
Covariance Type:            nonrobust   LLR p-value:                 0.0008785
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     24.0603      6.914      3.480      0.001      10.510      37.611
cpi            0.0744      0.023      3.291      0.001       0.030       0.119
pop           -0.1286      0.038     -3.349      0.001      -0.204      -0.053
==============================================================================</code></pre>
</div>
</div>
<p>We can compute odds ratios and other information by calling methods on the fitted result object. Below are the 95% confidence intervals of the odds ratio <span class="math inline">\(e^{\text{coef}}\)</span> of each coefficient:</p>
<div id="73340891" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>odds_ratios <span class="op">=</span> pd.DataFrame(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Odds Ratio"</span>: result2.params,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Lower CI"</span>: result2.conf_int()[<span class="dv">0</span>],</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Upper CI"</span>: result2.conf_int()[<span class="dv">1</span>],</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>odds_ratios <span class="op">=</span> np.exp(odds_ratios)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(odds_ratios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Odds Ratio      Lower CI      Upper CI
Intercept  2.813587e+10  36683.855503  2.157971e+16
cpi        1.077211e+00      1.030540  1.125997e+00
pop        8.793232e-01      0.815568  9.480629e-01</code></pre>
</div>
</div>
<p>Note these are no longer <em>log odds</em> we are looking at! We estimate with 95% confidence that the true odds ratio lies between the lower CI and upper CI for each coefficient. A larger odds ratio is associated with a larger probability that the unemployment rate is greater than 5%.</p>
</section>
<section id="poisson-regression" class="level4" data-number="9.3.7.3">
<h4 data-number="9.3.7.3" class="anchored" data-anchor-id="poisson-regression"><span class="header-section-number">9.3.7.3</span> Poisson Regression</h4>
<p>This type of regression is best suited for modeling the how the mean of a discrete variable depends on one or more predictors.</p>
<p>The log of the probability of success is modeled by:</p>
<p><span class="math inline">\(\log(\mu) = b_0 + b_1x_1 + ... + b_kx_k\)</span></p>
<p>where <span class="math inline">\(\mu\)</span> is the probability of success (the response variable). The intercept <code>b0</code> is assumed to be 0 if not provided in the model. We will use <code>.add_constant</code> to indicate that our model includes an intercept term.</p>
<p>Let’s use the <code>sunspots</code> dataset from <code>statsmodels</code>. This is a one variable dataset that counts the number of sunspots that occur in a given year (from 1700 - 2008). Note that the link function for Poisson regression is a log function, which means <span class="math inline">\(\log{E(Y)}=X\beta.\)</span></p>
<p>We first load an instance of a <code>statsmodels</code> dataset class, analogous to a <code>pandas</code> dataframe:</p>
<div id="2ddb265c" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="op">=</span> sm.datasets.sunspots.load_pandas()</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>df3 <span class="op">=</span> df3.data</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>df3[<span class="st">'YEAR'</span>] <span class="op">=</span> df3[<span class="st">'YEAR'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: x<span class="op">-</span><span class="dv">1700</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># YEAR is now number of years after 1700, scaling the data for better results</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>df3[<span class="st">'YEAR2'</span>] <span class="op">=</span> df3[<span class="st">'YEAR'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: x<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># YEAR2 is YEAR squared, used as additional predictor</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(df3[[<span class="st">'YEAR'</span>,<span class="st">'YEAR2'</span>]]) </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co"># .add_constant indicates that our model includes an intercept term</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> df3[<span class="st">'SUNACTIVITY'</span>]</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df3[[<span class="st">'YEAR'</span>,<span class="st">'YEAR2'</span>,<span class="st">'SUNACTIVITY'</span>]].head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   YEAR  YEAR2  SUNACTIVITY
0   0.0    0.0          5.0
1   1.0    1.0         11.0
2   2.0    4.0         16.0
3   3.0    9.0         23.0
4   4.0   16.0         36.0</code></pre>
</div>
</div>
<p>In the code above, we are altering our predictors a little bit from the orignal dataset; we are substracting the minimum year 1700 from all <code>YEAR</code> values so it is more centered. It is generally good practice to scale and center your data so that the model can have better fit. In our case this also aids the interpretability of the intercept coefficient we will see later. We are adding the varaible <code>YEAR2</code>, which is the number of years since 1700 squared to see if there is some non-linear relationship that may exist.</p>
<p>We can use the <code>.GLM</code> function with the <code>family='poisson'</code> argument to fit our model. Some important parameters:</p>
<ul>
<li><code>data.endog</code> acts as a series of observations for the dependent variable <span class="math inline">\(Y\)</span></li>
<li><code>data.exog</code> acts as a series of observations for each predictor</li>
<li><code>family</code> specifies the distribution appropriate for the model</li>
</ul>
<div id="28f33458" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>result3 <span class="op">=</span> sm.GLM(Y, X, family<span class="op">=</span>sm.families.Poisson()).fit()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result3.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:            SUNACTIVITY   No. Observations:                  309
Model:                            GLM   Df Residuals:                      306
Model Family:                 Poisson   Df Model:                            2
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -5548.3
Date:                Mon, 25 Mar 2024   Deviance:                       9460.6
Time:                        16:27:19   Pearson chi2:                 9.37e+03
No. Iterations:                     5   Pseudo R-squ. (CS):             0.8057
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.6781      0.026    140.479      0.000       3.627       3.729
YEAR           0.0003      0.000      0.747      0.455      -0.000       0.001
YEAR2       5.368e-06   1.13e-06      4.755      0.000    3.16e-06    7.58e-06
==============================================================================</code></pre>
</div>
</div>
<ul>
<li><strong>coef:</strong> In this model, increasing the <code>YEAR</code> seems to increase the log of the expected count of Sunspot activity (<code>SUNACTIVITY</code>) by a small amount; the expected count of sunspot activty increases by <span class="math inline">\(e^{.0003}\)</span> (note that increasing <code>YEAR</code> also increases <code>YEAR2</code> so we have to be careful with interpretability!) This model also suggests that the number of sunspots is for the year 1700 is estimated to be <span class="math inline">\(e^{3.6781}\approx39.57\)</span>, while the number of actual sunspots that year was 5.</li>
<li><strong>Deviance:</strong> two times the difference between the log-likelihood of a fitted GLM and the log-likelihood of a perfect model where fitted responses match observed responses. A greater deviance indicates a worse fit.</li>
<li><strong>Pearson chi2:</strong> measures the goodness-of-fit of the model based on the square deviations between observed and expected values based on the model. A large value suggests that the model does not fit well.</li>
</ul>
</section>
</section>
<section id="diagnostic-tests" class="level3" data-number="9.3.8">
<h3 data-number="9.3.8" class="anchored" data-anchor-id="diagnostic-tests"><span class="header-section-number">9.3.8</span> Diagnostic Tests</h3>
<p>Throughout the GLMs listed above, we can find different statistics to assess how well the model fits the data. They include:</p>
<ul>
<li><strong>Deviance</strong>: Measures the goodness-of-fit by taking the difference between the log-likelihood of a fitted GLM and the log-likelihood of a perfect model where fitted responses match observed responses. A larger deviance indicates a worse fit for the model. This is a test statistic for Likelihood-ratio tests compared to a chi-squared distribution with <span class="math inline">\(df=df_{\text{full}}-df_{\text{null}}\)</span>, for comparing a full model against a null model (or some reduced model) similar to a partial F-test.</li>
</ul>
<div id="862ce7d7" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Poisson Regression Deviance:"</span>, result3.deviance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Poisson Regression Deviance: 9460.616202027577</code></pre>
</div>
</div>
<ul>
<li><strong>Pearson’s chi-square test:</strong> This tests whether the predicted probabilities from the model differ significantly from the observed counts. The test statistic is calculated by taking the difference between the null deviance (deviance of a model with just the intercept term) and residual deviance (how well the response variable can be predicted by a model with a given number of predictors). Large Pearson’s chi-squares indicate poor fit.</li>
</ul>
<div id="86bad464" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Chi Squared Stat:"</span>,result3.pearson_chi2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Chi Squared Stat: 9368.0333091202</code></pre>
</div>
</div>
<ul>
<li><strong>Residual Plots:</strong> Like in linear regression, we can visually plot residuals to look for patterns that shouldn’t be there. There are different types of residuals that we can look at, such as deviance residuals:</li>
</ul>
<div id="fade0bc3" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>plt.scatter(df3[<span class="st">'YEAR'</span>],result3.resid_deviance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="statsmod_files/figure-html/cell-16-output-1.png" width="652" height="337" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="nonparametric-models" class="level3" data-number="9.3.9">
<h3 data-number="9.3.9" class="anchored" data-anchor-id="nonparametric-models"><span class="header-section-number">9.3.9</span> Nonparametric Models</h3>
<section id="kernel-density-estimation" class="level4" data-number="9.3.9.1">
<h4 data-number="9.3.9.1" class="anchored" data-anchor-id="kernel-density-estimation"><span class="header-section-number">9.3.9.1</span> Kernel Density Estimation</h4>
<p><code>statsmodels</code> has a non-parametric approach called kernel density estimation (KDE), which estimates the underlying probability of a given assortment of data points. KDE is used when you don’t have enough data points to form a parametric model. It estimates the density of continuous random variables, or extrapolates some continuous function from discrete counts. KDE is a non-parametric way to estimate the underlying distribution of data. The KDE weights all the distances of all data points relative to every location. The more data points there are at a given location, the higher the KDE estimate at that location. Points closer to a given location are generally weighted more than those further away. The shape of the kernel function itself indicates how the point distances are weighted. For example, a uniform kernel function will give equal weighting across all values within a bandwidth, whereas a triangle kernel function gives weighting dependent on linear distance.</p>
<p>KDE can be applied for univariate or multivariate data. <code>statsmodels</code> has two methods for this: - <code>sm.nonparametric.KDEunivariate</code>: For univariate data. This estimates the bandwidth using Scott’s rule unless specified otherwise. Much faster than using <code>.KDEMultivariate</code> due to its use of Fast Fourier Transforms on univariate, continuous data. - <code>sm.nonparametric.KDEMultivariate</code>: This applies to both univariate and multivariate data, but tends to be slower. Can use mixed types of data but requires specification.</p>
<p>Here we will demonstrate how to apply it to univariate data, based off of examples provided in the <a href="https://www.statsmodels.org/stable/examples/notebooks/generated/kernel_density.html#Comparing-kernel-functions">documentation</a>. We will generate a histogram of based off of <a href="https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/faithful">geyser waiting time</a> data from Rdatasets. This dataset records the waiting time between “Old Faithful” geyser’s eruptions in Yellowstone National Park. Our goal is to fit a KDE with a Gaussian kernel function to this data.</p>
<div id="a66658a6" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>df5 <span class="op">=</span> sm.datasets.get_rdataset(<span class="st">"faithful"</span>, <span class="st">"datasets"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>waiting_obs <span class="op">=</span> df5.data[<span class="st">'waiting'</span>] </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of data samples and histogram</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> fig.add_subplot()</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Count"</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Time (min)"</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>ax.hist(</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    waiting_obs,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    bins<span class="op">=</span><span class="dv">25</span>, </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"darkblue"</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    edgecolor<span class="op">=</span><span class="st">"w"</span>, </span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.8</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"Histogram"</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>ax.scatter(</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    waiting_obs,</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>    np.<span class="bu">abs</span>(np.random.randn(waiting_obs.size)),</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"orange"</span>,</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>    marker<span class="op">=</span><span class="st">"o"</span>,</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"Samples"</span>,</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"best"</span>)</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.35</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="statsmod_files/figure-html/cell-17-output-1.png" width="659" height="356" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Now we want to fit our KDE based on our <code>waiting_obs</code> sample:</p>
<div id="b5317154" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>kde <span class="op">=</span> sm.nonparametric.KDEUnivariate(waiting_obs)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>kde.fit()  <span class="co"># Estimate the densities</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Estimated Bandwidth:"</span>, kde.bw)  </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of data samples and histogram</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> fig.add_subplot()</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">"Count"</span>)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">"Time (min)"</span>)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>ax1.hist(</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    waiting_obs,</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    bins<span class="op">=</span><span class="dv">25</span>, </span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"darkblue"</span>,</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>    edgecolor<span class="op">=</span><span class="st">"w"</span>, </span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.8</span>,</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"Histogram"</span>,</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>ax1.scatter(</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>    waiting_obs,</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>    np.<span class="bu">abs</span>(np.random.randn(waiting_obs.size)),</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"orange"</span>,</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>    marker<span class="op">=</span><span class="st">"o"</span>,</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"Waiting times"</span>,</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> ax1.twinx()</span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a>ax2.plot(</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>    kde.support, </span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a>    kde.density, </span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a>    lw<span class="op">=</span><span class="dv">3</span>, </span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"KDE"</span>)</span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Joining legends</span></span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a>lines, labels <span class="op">=</span> ax1.get_legend_handles_labels()</span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a>lines2, labels2 <span class="op">=</span> ax2.get_legend_handles_labels()</span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a>ax2.legend(lines <span class="op">+</span> lines2, labels <span class="op">+</span> labels2, loc<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a>ax1.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.35</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Bandwidth: 4.693019309795263</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="statsmod_files/figure-html/cell-18-output-2.png" width="725" height="356" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>When fitting the KDE, a <code>kde.bw</code> or bandwidth parameter is returned. We can alter this to see how it affects the fit and smoothness of the curve. The smaller the bandwidth, the more jagged the estimated distribution becomes.</p>
<div id="73ab6d6d" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of data samples and histogram</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> fig.add_subplot()</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">"Count"</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">"Time (min)"</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>ax1.hist(</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    waiting_obs,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    bins<span class="op">=</span><span class="dv">25</span>, </span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"darkblue"</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    edgecolor<span class="op">=</span><span class="st">"w"</span>, </span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.8</span>,</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"Histogram"</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>ax1.scatter(</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    waiting_obs,</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    np.<span class="bu">abs</span>(np.random.randn(waiting_obs.size)),</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"orange"</span>,</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>    marker<span class="op">=</span><span class="st">"o"</span>,</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"Samples"</span>,</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the KDE for various bandwidths</span></span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> ax1.twinx()</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (bandwidth, color) <span class="kw">in</span> [(<span class="fl">0.5</span>,<span class="st">"cyan"</span>), (<span class="dv">4</span>,<span class="st">"#bbaa00"</span>), (<span class="dv">8</span>,<span class="st">"#ff79ff"</span>)]:</span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>    kde.fit(bw<span class="op">=</span>bandwidth)  <span class="co"># Estimate the densities</span></span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>    ax2.plot(</span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a>        kde.support,</span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a>        kde.density,</span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a>        <span class="st">"--"</span>,</span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>        lw<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>color,</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="ss">f"KDE from samples, bw = </span><span class="sc">{</span>bandwidth<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a>        alpha<span class="op">=</span><span class="fl">0.9</span></span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a>ax1.legend(loc<span class="op">=</span><span class="st">"best"</span>)</span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a>ax2.legend(loc<span class="op">=</span><span class="st">"best"</span>)</span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a>ax1.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.35</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="statsmod_files/figure-html/cell-19-output-1.png" width="716" height="356" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="references" class="level3" data-number="9.3.10">
<h3 data-number="9.3.10" class="anchored" data-anchor-id="references"><span class="header-section-number">9.3.10</span> References</h3>
<ul>
<li>Installing <code>statsmodels</code>:
<ul>
<li><a href="https://www.statsmodels.org/stable/install.html" class="uri">https://www.statsmodels.org/stable/install.html</a></li>
</ul></li>
<li><code>Rdatasets</code> repository and <code>statsmodels</code> datasets:
<ul>
<li><a href="https://github.com/vincentarelbundock/Rdatasets/blob/master/datasets.csv" class="uri">https://github.com/vincentarelbundock/Rdatasets/blob/master/datasets.csv</a></li>
<li><a href="https://cran.r-project.org/web/packages/causaldata/causaldata.pdf" class="uri">https://cran.r-project.org/web/packages/causaldata/causaldata.pdf</a></li>
<li><a href="https://hassavocadoboard.com/" class="uri">https://hassavocadoboard.com/</a></li>
<li><a href="https://www.statsmodels.org/stable/datasets/index.html" class="uri">https://www.statsmodels.org/stable/datasets/index.html</a></li>
<li><a href="https://www.statsmodels.org/stable/datasets/generated/sunspots.html" class="uri">https://www.statsmodels.org/stable/datasets/generated/sunspots.html</a></li>
<li><a href="https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/faithful" class="uri">https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/faithful</a></li>
</ul></li>
<li>NYC 311 Service Request Data:
<ul>
<li><a href="https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9/about_data" class="uri">https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9/about_data</a></li>
</ul></li>
<li>Getting help with <code>statsmodels</code>:
<ul>
<li><a href="https://www.statsmodels.org/stable/generated/statsmodels.tools.web.webdoc.html#statsmodels.tools.web.webdoc" class="uri">https://www.statsmodels.org/stable/generated/statsmodels.tools.web.webdoc.html#statsmodels.tools.web.webdoc</a></li>
<li><a href="https://www.statsmodels.org/stable/endog_exog.html" class="uri">https://www.statsmodels.org/stable/endog_exog.html</a></li>
</ul></li>
<li>Loading data, model fit, and summary procedure:
<ul>
<li><a href="https://www.statsmodels.org/stable/gettingstarted.html" class="uri">https://www.statsmodels.org/stable/gettingstarted.html</a></li>
</ul></li>
<li>Summary Data Interpretation:
<ul>
<li><a href="https://www.statology.org/a-simple-guide-to-understanding-the-f-test-of-overall-significance-in-regression/" class="uri">https://www.statology.org/a-simple-guide-to-understanding-the-f-test-of-overall-significance-in-regression/</a></li>
<li><a href="https://www.statology.org/linear-regression-p-value/" class="uri">https://www.statology.org/linear-regression-p-value/</a></li>
<li><a href="https://www.statology.org/omnibus-test/" class="uri">https://www.statology.org/omnibus-test/</a></li>
<li><a href="https://www.statisticshowto.com/jarque-bera-test/" class="uri">https://www.statisticshowto.com/jarque-bera-test/</a></li>
<li><a href="https://www.statology.org/how-to-report-skewness-kurtosis/" class="uri">https://www.statology.org/how-to-report-skewness-kurtosis/</a></li>
<li><a href="https://www.statology.org/interpret-log-likelihood/" class="uri">https://www.statology.org/interpret-log-likelihood/</a></li>
<li><a href="https://stackoverflow.com/questions/46700258/python-how-to-interpret-the-result-of-logistic-regression-by-sm-logit" class="uri">https://stackoverflow.com/questions/46700258/python-how-to-interpret-the-result-of-logistic-regression-by-sm-logit</a></li>
<li><a href="https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-what-are-pseudo-r-squareds/" class="uri">https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-what-are-pseudo-r-squareds/</a></li>
<li><a href="https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/" class="uri">https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/</a></li>
<li><a href="https://vulstats.ucsd.edu/chi-squared.html" class="uri">https://vulstats.ucsd.edu/chi-squared.html</a></li>
<li><a href="https://roznn.github.io/GLM/sec-deviance.html" class="uri">https://roznn.github.io/GLM/sec-deviance.html</a></li>
</ul></li>
<li>Generalized Linear Models:
<ul>
<li><a href="https://sscc.wisc.edu/sscc/pubs/glm-r/" class="uri">https://sscc.wisc.edu/sscc/pubs/glm-r/</a></li>
<li><a href="https://online.stat.psu.edu/stat504/lesson/6/6.1" class="uri">https://online.stat.psu.edu/stat504/lesson/6/6.1</a></li>
<li><a href="https://www.mygreatlearning.com/blog/generalized-linear-models/" class="uri">https://www.mygreatlearning.com/blog/generalized-linear-models/</a></li>
<li><a href="https://www.statsmodels.org/stable/examples/notebooks/generated/glm.html" class="uri">https://www.statsmodels.org/stable/examples/notebooks/generated/glm.html</a></li>
</ul></li>
<li>Logistic Regression:
<ul>
<li><a href="https://www.andrewvillazon.com/logistic-regression-python-statsmodels/" class="uri">https://www.andrewvillazon.com/logistic-regression-python-statsmodels/</a></li>
<li><a href="https://towardsdatascience.com/how-to-interpret-the-odds-ratio-with-categorical-variables-in-logistic-regression-5bb38e3fc6a8" class="uri">https://towardsdatascience.com/how-to-interpret-the-odds-ratio-with-categorical-variables-in-logistic-regression-5bb38e3fc6a8</a></li>
<li><a href="https://towardsdatascience.com/a-simple-interpretation-of-logistic-regression-coefficients-e3a40a62e8cf" class="uri">https://towardsdatascience.com/a-simple-interpretation-of-logistic-regression-coefficients-e3a40a62e8cf</a></li>
<li><a href="https://www.statology.org/interpret-log-likelihood/" class="uri">https://www.statology.org/interpret-log-likelihood/</a></li>
</ul></li>
<li>Poisson Regression:
<ul>
<li><a href="https://tidypython.com/poisson-regression-in-python/" class="uri">https://tidypython.com/poisson-regression-in-python/</a></li>
</ul></li>
<li>Non-parametric Methods:
<ul>
<li><a href="https://mathisonian.github.io/kde/" class="uri">https://mathisonian.github.io/kde/</a></li>
<li><a href="https://www.statsmodels.org/stable/nonparametric.html" class="uri">https://www.statsmodels.org/stable/nonparametric.html</a></li>
<li><a href="https://www.statsmodels.org/dev/generated/statsmodels.nonparametric.kde.KDEUnivariate.html" class="uri">https://www.statsmodels.org/dev/generated/statsmodels.nonparametric.kde.KDEUnivariate.html</a></li>
<li><a href="https://www.statsmodels.org/dev/generated/statsmodels.nonparametric.kernel_density.KDEMultivariate.html" class="uri">https://www.statsmodels.org/dev/generated/statsmodels.nonparametric.kernel_density.KDEMultivariate.html</a></li>
<li><a href="https://www.statsmodels.org/stable/examples/notebooks/generated/kernel_density.html" class="uri">https://www.statsmodels.org/stable/examples/notebooks/generated/kernel_density.html</a></li>
</ul></li>
<li>Diagnostic tests:
<ul>
<li><a href="https://www.statsmodels.org/stable/stats.html#residual-diagnostics-and-specification-tests" class="uri">https://www.statsmodels.org/stable/stats.html#residual-diagnostics-and-specification-tests</a></li>
<li><a href="https://bookdown.org/ltupper/340f21_notes/deviance-and-residuals.html" class="uri">https://bookdown.org/ltupper/340f21_notes/deviance-and-residuals.html</a></li>
<li><a href="https://www.statology.org/null-residual-deviance/" class="uri">https://www.statology.org/null-residual-deviance/</a></li>
</ul></li>
<li>Data Visualization:
<ul>
<li><a href="https://stackoverflow.com/questions/5484922/secondary-axis-with-twinx-how-to-add-to-legend" class="uri">https://stackoverflow.com/questions/5484922/secondary-axis-with-twinx-how-to-add-to-legend</a></li>
</ul></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./visualization.html" class="pagination-link" aria-label="Visualization">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./supervised.html" class="pagination-link" aria-label="Supervised Learning">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Supervised Learning</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>